"""add chat class

Revision ID: 096f7a5f94a6
Revises: 1acf09f298c5
Create Date: 2019-12-05 17:45:03.007430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096f7a5f94a6'
down_revision = '1acf09f298c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
