"""migrations

Revision ID: 422698344ab3
Revises: 872269c51d15
Create Date: 2019-12-05 15:33:33.833345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422698344ab3'
down_revision = '872269c51d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
